"""
Family Relationship terminology constants.

Ported from: Satusehat\Integration\Terminology\FamilyRelationship
Source: satusehat-integration (Laravel)

Contains HL7 v3 family relationship codes.
"""
from __future__ import annotations


class FamilyRelationship:
    """
    Static family relationship codes from HL7 v3 RoleCode.

    Ported from Laravel static class FamilyRelationship.
    """

    relationship_codes: dict[str, str] = {
        "FAMMEMB": "family member",
        "CHILD": "child",
        "CHLDADOPT": "adopted child",
        "DAUADOPT": "adopted daughter",
        "SONADOPT": "adopted son",
        "CHLDFOST": "foster child",
        "DAUFOST": "foster daughter",
        "SONFOST": "foster son",
        "DAUC": "daughter",
        "DAU": "natural daughter",
        "STPDAU": "stepdaughter",
        "NCHILD": "natural child",
        "SON": "natural son",
        "SONC": "son",
        "STPSON": "stepson",
        "STPCHLD": "step child",
        "EXT": "extended family member",
        "AUNT": "aunt",
        "MAUNT": "maternal aunt",
        "PAUNT": "paternal aunt",
        "COUSN": "cousin",
        "MCOUSN": "maternal cousin",
        "PCOUSN": "paternal cousin",
        "GGRPRN": "great grandparent",
        "GGRFTH": "great grandfather",
        "MGGRFTH": "maternal great-grandfather",
        "PGGRFTH": "paternal great-grandfather",
        "GGRMTH": "great grandmother",
        "MGGRMTH": "maternal great-grandmother",
        "PGGRMTH": "paternal great-grandmother",
        "GRNDCHILD": "grandchild",
        "GRNDDAU": "granddaughter",
        "GRNDSON": "grandson",
        "GRPRN": "grandparent",
        "GRFTH": "grandfather",
        "MGRFTH": "maternal grandfather",
        "PGRFTH": "paternal grandfather",
        "GRMTH": "grandmother",
        "MGRMTH": "maternal grandmother",
        "PGRMTH": "paternal grandmother",
        "INLAW": "inlaw",
        "CHLDINLAW": "child-in-law",
        "DAUINLAW": "daughter in-law",
        "SONINLAW": "son in-law",
        "PRNINLAW": "parent in-law",
        "FTHINLAW": "father-in-law",
        "MTHINLAW": "mother-in-law",
        "SIBINLAW": "sibling in-law",
        "BROINLAW": "brother-in-law",
        "SISINLAW": "sister-in-law",
        "NIENEPH": "niece/nephew",
        "NEPHEW": "nephew",
        "NIECE": "niece",
        "UNCLE": "uncle",
        "MUNCLE": "maternal uncle",
        "PUNCLE": "paternal uncle",
        "PRN": "parent",
        "ADOPTP": "adoptive parent",
        "ADOPTF": "adoptive father",
        "ADOPTM": "adoptive mother",
        "FTH": "father",
        "FTHFOST": "foster father",
        "NFTH": "natural father",
        "STPFTH": "stepfather",
        "MTH": "mother",
        "GESTM": "gestational mother",
        "MTHFOST": "foster mother",
        "NMTH": "natural mother",
        "STPMTH": "stepmother",
        "NPRN": "natural parent",
        "PRNFOST": "foster parent",
        "STPPRN": "step parent",
        "SIB": "sibling",
        "BRO": "brother",
        "HBRO": "half-brother",
        "NBRO": "natural brother",
        "STPBRO": "stepbrother",
        "HSIB": "half-sibling",
        "HSIS": "half-sister",
        "NSIB": "natural sibling",
        "NSIS": "natural sister",
        "SIS": "sister",
        "STPSIS": "stepsister",
        "STPSIB": "step sibling",
        "SIGOTHR": "significant other",
        "DOMPART": "domestic partner",
        "FMRSPS": "former spouse",
        "SPS": "spouse",
        "HUSB": "husband",
        "WIFE": "wife",
    }
