"""
Medication terminology constants.

Ported from: Satusehat\Integration\Terminology\MedicationTerminology
Source: satusehat-integration (Laravel)

Contains medication form codes, drug form codes, route codes,
timing codes, and other medication-related FHIR terminology.
"""
from __future__ import annotations


class MedicationTerminology:
    """
    Static medication terminology constants from SATUSEHAT / HL7 / SNOMED.

    Ported from Laravel static class MedicationTerminology.
    These are read-only lookup dictionaries.
    """

    medication_form: dict[str, str] = {
        "BS001": "Aerosol Foam",
        "BS002": "Aerosol Metered Dose",
        "BS003": "Aerosol Spray",
        "BS004": "Oral Spray",
        "BS005": "Buscal Spray",
        "BS006": "Transdermal Spray",
        "BS007": "Topical Spray",
        "BS008": "Serbuk Spray",
        "BS009": "Eliksir",
        "BS010": "Emulsi",
        "BS011": "Enema",
        "BS012": "Gas",
        "BS013": "Gel",
        "BS014": "Gel Mata",
        "BS015": "Granul Effervescent",
        "BS016": "Granula",
        "BS017": "Intra Uterine Device (IUD)",
        "BS018": "Implant",
        "BS019": "Kapsul",
        "BS020": "Kapsul Lunak",
        "BS021": "Kapsul Pelepasan Lambat",
        "BS022": "Kaplet",
        "BS023": "Kaplet Salut Selaput",
        "BS024": "Kaplet Salut Enterik",
        "BS025": "Kaplet Salut Gula",
        "BS026": "Kaplet Pelepasan Lambat",
        "BS027": "Kaplet Pelepasan Cepat",
        "BS028": "Kaplet Kunyah",
        "BS029": "Kaplet Kunyah Salut Selaput",
        "BS030": "Krim",
        "BS031": "Krim Lemak",
        "BS032": "Larutan",
        "BS033": "Larutan Inhalasi",
        "BS034": "Larutan Injeksi",
        "BS035": "Infus",
        "BS036": "Obat Kumur",
        "BS037": "Ovula",
        "BS038": "Pasta",
        "BS039": "Pil",
        "BS040": "Patch",
        "BS041": "Pessary",
        "BS042": "Salep",
        "BS043": "Salep Mata",
        "BS044": "Sampo",
        "BS045": "Semprot Hidung",
        "BS046": "Serbuk Aerosol",
        "BS047": "Serbuk Oral",
        "BS048": "Serbuk Inhaler",
        "BS049": "Serbuk Injeksi",
        "BS050": "Serbuk Injeksi Liofilisasi",
        "BS051": "Serbuk Infus",
        "BS052": "Serbuk Obat Luar / Serbuk Tabur",
        "BS053": "Serbuk Steril",
        "BS054": "Serbuk Effervescent",
        "BS055": "Sirup",
        "BS056": "Sirup Kering",
        "BS057": "Sirup Kering Pelepasan Lambat",
        "BS058": "Subdermal Implants",
        "BS059": "Supositoria",
        "BS060": "Suspensi",
        "BS061": "Suspensi Injeksi",
        "BS062": "Suspensi / Cairan Obat Luar",
        "BS063": "Cairan Steril",
        "BS064": "Cairan Mata",
        "BS065": "Cairan Diagnostik",
        "BS066": "Tablet",
        "BS067": "Tablet Effervescent",
        "BS068": "Tablet Hisap",
        "BS069": "Tablet Kunyah",
        "BS070": "Tablet Pelepasan Cepat",
        "BS071": "Tablet Pelepasan Lambat",
        "BS072": "Tablet Disintegrasi Oral",
        "BS073": "Tablet Dispersibel",
        "BS074": "Tablet Cepat Larut",
        "BS075": "Tablet Salut Gula",
        "BS076": "Tablet Salut Enterik",
        "BS077": "Tablet Salut Selaput",
        "BS078": "Tablet Sublingual",
        "BS079": "Tablet Sublingual Pelepasan Lambat",
        "BS080": "Tablet Vaginal",
        "BS081": "Tablet Lapis",
        "BS082": "Tablet Lapis Lepas Lambat",
        "BS083": "Chewing Gum",
        "BS084": "Tetes Mata",
        "BS085": "Tetes Hidung",
        "BS086": "Tetes Telinga",
        "BS087": "Tetes Oral (Oral Drops)",
        "BS088": "Tetes Mata Dan Telinga",
        "BS089": "Transdermal",
        "BS090": "Transdermal Urethral",
        "BS091": "Tulle/Plester Obat",
        "BS092": "Vaginal Cream",
        "BS093": "Vaginal Gel",
        "BS094": "Vaginal Douche",
        "BS095": "Vaginal Ring",
        "BS096": "Vaginal Tissue",
        "BS097": "Suspensi Inhalasi",
        "MF000001": "Orodispersible Film",
    }

    drug_form: dict[str, dict[str, str]] = {
        "APPFUL": {"display": "Applicatorful", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "DROP": {"display": "Drops", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "NDROP": {"display": "Nasal Drops", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "OPDROP": {"display": "Ophthalmic Drops", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "ORDROP": {"display": "Oral Drops", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "OTDROP": {"display": "Otic Drops", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "PUFF": {"display": "Puff", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "SCOOP": {"display": "Scoops", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "SPRY": {"display": "Sprays", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "AER": {"display": "Aerosol", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "BAINHL": {"display": "Breath Activated Inhaler", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "INHLSOL": {"display": "Inhalant Solution", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "MDINHL": {"display": "Metered Dose Inhaler", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "NASSPRY": {"display": "Nasal Spray", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "DERMSPRY": {"display": "Dermal Spray", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "FOAM": {"display": "Foam", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "FOAMAPL": {"display": "Foam with Applicator", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "INHL": {"display": "Inhalant", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "BAINHLPWD": {"display": "Breath Activated Powder Inhaler", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "INHLPWD": {"display": "Inhalant Powder", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "MDINHLPWD": {"display": "Metered Dose Powder Inhaler", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "NASINHL": {"display": "Nasal Inhalant", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "ORINHL": {"display": "Oral Inhalant", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "PWDSPRY": {"display": "Powder Spray", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "SOL": {"display": "Solution", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "IVSOL": {"display": "Intravenous Solution", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "ORALSOL": {"display": "Oral Solution", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "ELIXIR": {"display": "Elixir", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "SYRUP": {"display": "Syrup", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "CRM": {"display": "Cream", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "NASCRM": {"display": "Nasal Cream", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "OPCRM": {"display": "Ophthalmic Cream", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "TOPCRM": {"display": "Topical Cream", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "VAGCRM": {"display": "Vaginal Cream", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "LTN": {"display": "Lotion", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "TOPLTN": {"display": "Topical Lotion", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "OINT": {"display": "Ointment", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "NASOINT": {"display": "Nasal Ointment", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "OPOINT": {"display": "Ophthalmic Ointment", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "TOPOINT": {"display": "Topical Ointment", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "VAGOINT": {"display": "Vaginal Ointment", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "GEL": {"display": "Gel", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "NASGEL": {"display": "Nasal Gel", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "OPGEL": {"display": "Ophthalmic Gel", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "TOPGEL": {"display": "Topical Gel", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "VAGGEL": {"display": "Vaginal Gel", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "PASTE": {"display": "Paste", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "SUSP": {"display": "Suspension", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "OPSUSP": {"display": "Ophthalmic Suspension", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "ORSUSP": {"display": "Oral Suspension", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "CAP": {"display": "Capsule", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "ORCAP": {"display": "Oral Capsule", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "ENTCAP": {"display": "Enteric Coated Capsule", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "ERECAP": {"display": "Extended Release Capsule", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "TAB": {"display": "Tablet", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "ORTAB": {"display": "Oral Tablet", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "BUCTAB": {"display": "Buccal Tablet", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "CHEWTAB": {"display": "Chewable Tablet", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "ECTAB": {"display": "Enteric Coated Tablet", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "ERTAB": {"display": "Extended Release Tablet", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "SLTAB": {"display": "Sublingual Tablet", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "VAGTAB": {"display": "Vaginal Tablet", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "POWD": {"display": "Powder", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "TOPPWD": {"display": "Topical Powder", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "SUPP": {"display": "Suppository", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "RECSUPP": {"display": "Rectal Suppository", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "VAGSUPP": {"display": "Vaginal Suppository", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "SWAB": {"display": "Swab", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "WAFER": {"display": "Wafer", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "PATCH": {"display": "Patch", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "TPATCH": {"display": "Transdermal Patch", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "TPATHWK": {"display": "Weekly Transdermal Patch", "system": "http://terminology.hl7.org/CodeSystem/v3-orderableDrugForm"},
        "738998008": {"display": "Emulsion", "system": "http://snomed.info/sct"},
        "763824009": {"display": "Gas", "system": "http://snomed.info/sct"},
        "442015005": {"display": "Intrauterine dose form", "system": "http://snomed.info/sct"},
        "385286003": {"display": "Implant", "system": "http://snomed.info/sct"},
        "385174007": {"display": "Pessary", "system": "http://snomed.info/sct"},
        "764296002": {"display": "Prolonged-release", "system": "http://snomed.info/sct"},
        "761877007": {"display": "Effervescent tablet", "system": "http://snomed.info/sct"},
        "385057009": {"display": "Film-coated tablet", "system": "http://snomed.info/sct"},
        "385292009": {"display": "Vaginal dose form", "system": "http://snomed.info/sct"},
    }

    medicationrequest_status_reason: dict[str, str] = {
        "altchoice": "Try another treatment first",
        "clarif": "Prescription requires clarification",
        "drughigh": "Drug level too high",
        "hospadm": "Admission to hospital",
        "labint": "Lab interference issues",
        "non-avail": "Patient not available",
        "preg": "Parent is pregnant/breast feeding",
        "salg": "Allergy",
        "sddi": "Drug interacts with another drug",
        "sdupther": "Duplicate therapy",
        "sintol": "Suspected intolerance",
        "surg": "Patient scheduled for surgery",
        "washout": "Waiting for old drug to wash out",
    }

    medication_request_dispense_category: dict[str, str] = {
        "inpatient": "Inpatient",
        "outpatient": "Outpatient",
        "community": "Community",
        "discharge": "Discharge",
    }

    course_of_therapy_type: dict[str, str] = {
        "continuous": "Continuous long term therapy",
        "acute": "Short course (acute) therapy",
        "seasonal": "Seasonal",
    }

    time_interval: dict[str, str] = {
        "ms": "milliseconds",
        "s": "seconds",
        "min": "minutes",
        "h": "hours",
        "d": "days",
        "wk": "weeks",
        "mo": "months",
        "a": "years",
    }

    substitution_reason: dict[str, str] = {
        "E": "equivalent",
        "EC": "equivalent composition",
        "BC": "brand composition",
        "G": "generic composition",
        "TE": "therapeutic equivalence",
        "TB": "therapeutic brand",
        "TG": "therapeutic generic",
        "F": "formulary",
        "N": "none",
    }

    timing: dict[str, str] = {
        "BID": "twice a day",
        "TID": "three times a day",
        "QID": "four times a day",
        "AM": "morning",
        "PM": "evening",
        "QOD": "every other day",
        "Q1H": "every hour",
        "Q2H": "every 2 hours",
        "Q3H": "every 3 hours",
        "Q4H": "every 4 hours",
        "Q6H": "every 6 hours",
        "Q8H": "every 8 hours",
        "BED": "bedtime",
        "WK": "weekly",
        "MO": "monthly",
    }

    # SNOMED CT route codes (partial — maps code -> display)
    route_snomed: dict[int, str] = {
        697971008: "Arteriovenous fistula route",
        420254004: "Body cavity route",
        54471007: "Buccal route",
        372450004: "Endocervical route",
        372452007: "Endotracheopulmonary route",
        417985001: "Enteral route",
        404820008: "Epidural route",
        372453002: "Extra-amniotic route",
        372458006: "Gastroenteral route",
        127491009: "Gastrostomy route",
        372468001: "Intraocular route",
        417255000: "Intraosseous route",
        38239002: "Intraperitoneal route",
        372469009: "Intrapleural route",
        72607000: "Intrathecal route",
        47625008: "Intravenous route",
        46713006: "Nasal route",
        372472002: "Ocular route",
        54485002: "Ophthalmic route",
        26643006: "Oral route",
        372473007: "Oromucosal route",
        37839007: "Sublingual route",
        10547007: "Otic route",
        78421000: "Intramuscular route",
        34206005: "Subcutaneous route",
        37161004: "Rectal route",
        419631009: "Intraovarian route",
        418114005: "Intravenous central route",
        419993007: "Intravenous peripheral route",
    }
